from . import sale_order
from . import plan_sale_order
from . import plan_sale_order_line
from . import res_config_settings
from . import crm_lead
from . import crm_team
from . import detailed_report
from . import target_assessment_report
from . import team_sale_rp
